require 'opal'
require 'opal-jquery'
require 'native'
require 'promise'

require 'paggio'
require 'browser/setup/mini'
require 'browser/delay'
require 'browser/interval'
require 'browser/immediate'
require 'browser/storage'
require 'browser/blob'
require 'browser/socket'
require 'browser/history'
require 'browser/navigator'
require 'browser/event/all'
require 'browser/dom/builder'
require 'browser/dom/mutation_observer'
require 'browser/dom/element/custom'
require 'browser/canvas'

# require 'opal-parser'

# for vega-support
# require 'browser/http'
# require 'browser/effects'
# require 'browser/animation_frame'
